[package]
name = "preearnings-call-setup"
version = "0.1.0"
authors = ["Daniel Imfeld <daniel@danielimfeld.com>"]

[dependencies]
chrono = "0.4.0
crossbeam = "0.3.2"
csv = "1.0.0-beta.5"
failure="0.1.1"
serde = "1.0.9"
serde_derive = "1.0.9"
slog = "2.1"
sloggers="0.2.6"
reqwest="0.8.4"